# Elemental Cores Config for Minecraft 1.21.5

# Cooldown times in seconds
cooldowns:
  normal: 12
  shift: 18

# Whether to allow PvP with core abilities
allow-pvp: true

# Tier multipliers (damage, effects)
tier-multipliers:
  1: 1.0
  2: 1.3
  3: 1.7
