name: ElementalCores
version: 1.21.5
main: com.elementalcores.ElementalCores
api-version: 1.21
softdepend: [ItemsAdder]
commands:
  core:
    description: Main command for Elemental Cores plugin
    usage: /core <give|info|reload>
    permission: elementalcores.use
permissions:
  elementalcores.use:
    description: Allows using core commands
    default: true
  elementalcores.admin:
    description: Allows using admin commands
    default: op
